### ISSUE TITLE
1.1.0 should have been 2.0.0 due to semver-major changes

### ISSUE THREAD

**Issue by aphix** [mdb/madison#10]
This was a semver major change however the package received only a minor version bump.

Anyone with '^' carrots in their package json will have just broken their app by using your package from 1.0.2 (this just bit me).

While the change is understandable, completely removing the getStateAbbrSync method and renaming it to getStateAbbr (_which was previously async!_) without properly incrementing the package version will likely cause others to have issues as well.

Not to mention the potentially very obscure/silent bugs that others may experience who've previously expected a callback method to fire from the async version that will no longer be hit.

I hope this note may help someone else out.

@mdb, please keep users of your library in mind when making future changes.

Thanks.

**Comment by mdb** [comment]
@aphix Thanks for pointing this out to me; you're completely right and I apologize. Do you have any opinions on how best to move forward? Do you recommend I `npm unpublish` and re-publish as `2.0.0`?

**Comment by mdb** [comment]
@aphix I have published the latest version as `2.0.0`. Please let me know if you'd also like me to `npm unpublish` any versions.

**Comment by aphix** [comment]
Thanks @mdb!

Unpublishing would likely save anyone naively `npm install`ing with a `^` carrot in there from getting something broken, so I'm all for it. If that's too much of a pain, or you're worried about further confusion/breakage, you could add a deprecation flag with a message/link to the readme to make users aware of the change and then they can decide to do whatever they want.

Whatever the case, I think you should make a note on the readme making clear what the changes are, something like:

**Version 2.0.0 Breaking Changes:**

\*Sync methods have been renamed to no longer have the "Sync" suffix, and async method versions have been removed to simplify the API (no async calls were needed, we simply load all the states into memory via json).

To clarify: All previously async methods now simply return a value synchronously, and do not take a callback (it won't be used if you pass one in!). All usages of previously synchronous methods can be upgraded by simply removing the "Sync" suffix and will continue to work the same.

---

I'd also consider throwing an error if someone passes in a func as a 2nd arg to the previously-async methods just to make it super obvious what's happening.

Thanks again for your work and quick response.

**Comment by andrew-st-angelo-77media** [comment]
Has this really been live in NPM since April (2019)?  Or was the GitHub Release published back in April and NPM wasn't updated until recently?

BTW, I vote for unpublishing the breaking change.  But we'll be migrating to 2.0.0 and using the new contract, anyway.

**Comment by mdb** [comment]
@andrew-st-angelo-77media @aphix -

Thanks for the feedback. I was unable to `npm unpublish` `1.1.0`:

```bash
$ npm unpublish madison@1.1.0
npm ERR! unpublish Failed to update data
npm ERR! code E400
npm ERR! You can no longer unpublish this version. Please deprecate it instead
npm ERR! npm deprecate madison@1.1.0 "this version has been deprecated" : 23-b8c7989b43fd48b406af7810285f56bf
```

However, I did deprecate 1.1.0 and also added a `README` comment:
* https://github.com/mdb/madison/#version-200-breaking-changes
* https://www.npmjs.com/package/madison/v/1.1.0

Given the `README` note and the 1.1.0 deprecation, do you all feel comfortable with me closing this issue?

**Comment by aphix** [comment]
Sounds good; feel free to close. Thanks for following up on this one.
